// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.3
// source: context.proto

package context

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 网络层错误代码
type Code int32

const (
	Code_SUCCESS          Code = 0
	Code_ERR_CHECKSUM     Code = 1 // 校验失败
	Code_ERR_GET_HEAD     Code = 2 // 获取 head 失败
	Code_ERR_GET_DATALEN  Code = 3 // 获取 dataLen 失败
	Code_ERR_GET_CHECKSUM Code = 4 // 获取 checkSum 失败
	Code_ERR_GET_DATA     Code = 5 // 获取 data 失败
	Code_ERR_UNPACK_HEAD  Code = 6 // 解包失败
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0: "SUCCESS",
		1: "ERR_CHECKSUM",
		2: "ERR_GET_HEAD",
		3: "ERR_GET_DATALEN",
		4: "ERR_GET_CHECKSUM",
		5: "ERR_GET_DATA",
		6: "ERR_UNPACK_HEAD",
	}
	Code_value = map[string]int32{
		"SUCCESS":          0,
		"ERR_CHECKSUM":     1,
		"ERR_GET_HEAD":     2,
		"ERR_GET_DATALEN":  3,
		"ERR_GET_CHECKSUM": 4,
		"ERR_GET_DATA":     5,
		"ERR_UNPACK_HEAD":  6,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_context_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_context_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{0}
}

// 服务传输上下文
type Context struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result    Code   `protobuf:"varint,1,opt,name=result,proto3,enum=Code" json:"result,omitempty"` // 返回码
	Session   uint32 `protobuf:"varint,2,opt,name=session,proto3" json:"session,omitempty"`         // 登录后会获得session
	ServiceId uint32 `protobuf:"varint,3,opt,name=serviceId,proto3" json:"serviceId,omitempty"`     // 服务id
	MethodId  uint32 `protobuf:"varint,4,opt,name=methodId,proto3" json:"methodId,omitempty"`       // 方法id
	Data      []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`                // 传输的数据
}

func (x *Context) Reset() {
	*x = Context{}
	if protoimpl.UnsafeEnabled {
		mi := &file_context_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_context_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{0}
}

func (x *Context) GetResult() Code {
	if x != nil {
		return x.Result
	}
	return Code_SUCCESS
}

func (x *Context) GetSession() uint32 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *Context) GetServiceId() uint32 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *Context) GetMethodId() uint32 {
	if x != nil {
		return x.MethodId
	}
	return 0
}

func (x *Context) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_context_proto protoreflect.FileDescriptor

var file_context_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x90, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1d, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x05, 0x2e, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x2a, 0x89, 0x01, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x52, 0x52, 0x5f,
	0x43, 0x48, 0x45, 0x43, 0x4b, 0x53, 0x55, 0x4d, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x52,
	0x52, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x48, 0x45, 0x41, 0x44, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f,
	0x45, 0x52, 0x52, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x4c, 0x45, 0x4e, 0x10,
	0x03, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x52, 0x52, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x45,
	0x43, 0x4b, 0x53, 0x55, 0x4d, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x52, 0x52, 0x5f, 0x47,
	0x45, 0x54, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x10, 0x05, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x52, 0x52,
	0x5f, 0x55, 0x4e, 0x50, 0x41, 0x43, 0x4b, 0x5f, 0x48, 0x45, 0x41, 0x44, 0x10, 0x06, 0x42, 0x0b,
	0x5a, 0x09, 0x2e, 0x3b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_context_proto_rawDescOnce sync.Once
	file_context_proto_rawDescData = file_context_proto_rawDesc
)

func file_context_proto_rawDescGZIP() []byte {
	file_context_proto_rawDescOnce.Do(func() {
		file_context_proto_rawDescData = protoimpl.X.CompressGZIP(file_context_proto_rawDescData)
	})
	return file_context_proto_rawDescData
}

var file_context_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_context_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_context_proto_goTypes = []interface{}{
	(Code)(0),       // 0: Code
	(*Context)(nil), // 1: Context
}
var file_context_proto_depIdxs = []int32{
	0, // 0: Context.result:type_name -> Code
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_context_proto_init() }
func file_context_proto_init() {
	if File_context_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_context_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Context); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_context_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_context_proto_goTypes,
		DependencyIndexes: file_context_proto_depIdxs,
		EnumInfos:         file_context_proto_enumTypes,
		MessageInfos:      file_context_proto_msgTypes,
	}.Build()
	File_context_proto = out.File
	file_context_proto_rawDesc = nil
	file_context_proto_goTypes = nil
	file_context_proto_depIdxs = nil
}
